### ISSUE TITLE
Calling function 'ImageUploadModule', function calls are not supported

### ISSUE THREAD

**Issue by nitishkumarnitc** [aberezkin/ng2-image-upload#16] opened 2017-01-10 13:43 UTC
ERROR in Error encountered resolving symbol values statically. Calling function 'ImageUploadModule', function calls are not supported. Consider replacing the function or lambda with a r
eference to an exported function, resolving symbol AppModule in C:/Users/nitkumar/web/src/app/app.module.ts, resolving symbol AppModule in C:/Users/nitkumar/web/src/app/app.module.ts

**Comment by aberezkin** [comment] 2017-01-10 22:56
Can you provide some code?

**Comment by aberezkin** [comment] 2017-01-10 23:35
Are you using Angular CLI?

**Comment by nitishkumarnitc** [comment] 2017-01-11 10:21
Yes, I am using Angular CLI.
Steps taken by me:
1. npm install angular2-image-upload --save
2. app-module.ts-> import {ImageUploadModule} from "angular2-image-upload";
3. Imports:[... ImageUploadModule.forRoot()...]

Error: ERROR in Error encountered resolving symbol values statically. Calling function 'ImageUploadModule', function calls are not supported. Consider replacing the function or lambda with a r
eference to an exported function, resolving symbol AppModule in C:/Users/nitkumar/web/src/app/app.module.ts, resolving symbol AppModule in C:/Users/nitkumar/web/src/app/app.module.ts

**Comment by aberezkin** [comment] 2017-01-11 15:51
Duplicate of #13

**Closed by aberezkin** 2017-01-11 15:51 UTC
Labels: duplicate
