### ISSUE TITLE
Showing 2 images after upload if specify uploadedFiles

### ISSUE THREAD

**Issue by kotromeo** [aberezkin/ng2-image-upload#163] opened 2017-11-22 04:47 UTC
After uploading file i see two images

![admin panel 2017-11-22 07-43-07 1](https://user-images.githubusercontent.com/6111034/33110539-89267992-cf59-11e7-80e8-9c64741a79d2.png)

`<image-upload
[max]="1"
[extensions]="['jpg','png']"
[url]="'http://apitc.innoline.pro/api/v1/Image/'"
[headers]="{'Authorization': token}"
[partName]="'file'"
[uploadedFiles]="model.imageId ? ['http://apitc.innoline.pro/api/v1/Image/' + model.imageId + '.jpg'] : []"
(uploadFinished)="onUploadFinished($event, 'imageId')"
(removed)="onRemoved($event, 'imageId')"
[buttonCaption]="(model.imageId ? 'removeBeforeUpload' : 'uploadFile') | translate"
[dropBoxMessage]="'dropYourImagesHere' | translate"
></image-upload>`

after upload i'm changing model

`onUploadFinished($event, fieldName) {
        let self = this;
        if($event.serverResponse.json().success) {
            self.model[fieldName] = $event.serverResponse.json().data;
        }
    }`

as i see in inspector here 2 images - one is base 64 and second is my from uploadedFiles

**Comment by sancho21** [comment] 2017-12-19 10:47
This is a bug that can be fixed by modifying image-upload.component.ts on:

```
private processUploadedFiles() {
    this.files = []; // Should be added

```

**Comment by UncleDave** [comment] 2017-12-19 11:49
This is not a bug.
`[uploadedFiles]` takes an array of files that is separate from the component's internal list of uploaded files. If you upload a file using the component and manually add it to your `[uploadedFiles]` array you will get two images.

The suggested usage for `[uploadedFiles]` is to load files that should be present when the component is rendered - from a server or otherwise. The component internally tracks uploaded files and this input property shouldn't be used for that.

**Closed by UncleDave** 2017-12-19 11:49 UTC

**Comment by sancho21** [comment] 2017-12-19 11:58
If we clear property 'files' in the first line of the method, it will break
the logic?

I didn't modify the uploadedFiles property. When rebinding the property,
the old files (in rendered component)  remains, plus the values defined in
uploadProperties.

On Dec 19, 2017 7:49 PM, "Dave Pringle" <notifications@github.com> wrote:

This is not a bug.
[uploadedFiles] takes an array of files that is separate from the
component's internal list of uploaded files. If you upload a file using the
component and manually add it to your [uploadedFiles] array you will get
two images.

The suggested usage for [uploadedFiles] is to load files that should be
present when the component is rendered - from a server or otherwise. The
component internally tracks uploaded files and this input property
shouldn't be used for that.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/aberezkin/ng2-image-upload/issues/163#issuecomment-352727513>,
or mute the thread

**Comment by jihin** [comment] 2020-05-02 14:02
> $event

I am getting same error, did you got any solution

**Comment by jihin** [comment] 2020-05-02 14:03
> After uploading file i see two images
> 
> ![admin panel 2017-11-22 07-43-07 1](https://user-images.githubusercontent.com/6111034/33110539-89267992-cf59-11e7-80e8-9c64741a79d2.png)
> 
> `<image-upload
> [max]="1"
> [extensions]="['jpg','png']"
> [url]="'http://apitc.innoline.pro/api/v1/Image/'"
> [headers]="{'Authorization': token}"
> [partName]="'file'"
> [uploadedFiles]="model.imageId ? ['http://apitc.innoline.pro/api/v1/Image/' + model.imageId + '.jpg'] : []"
> (uploadFinished)="onUploadFinished($event, 'imageId')"
> (removed)="onRemoved($event, 'imageId')"
> [buttonCaption]="(model.imageId ? 'removeBeforeUpload' : 'uploadFile') | translate"
> [dropBoxMessage]="'dropYourImagesHere' | translate"
> 
> > `
> 
> after upload i'm changing model
> 
> `onUploadFinished($event, fieldName) { let self = this; if($event.serverResponse.json().success) { self.model[fieldName] = $event.serverResponse.json().data; } }`
> 
> as i see in inspector here 2 images - one is base 64 and second is my from uploadedFiles

I am getting same error, did you got any solution
