### ISSUE TITLE
Upload using browse button.

### ISSUE THREAD

**Issue by armangevorgyan** [aberezkin/ng2-image-upload#115] opened 2017-07-24 09:26 UTC
After image upload with browse button, second time(or 3 time) browse button doesn't work(i mean method doesn't called)

**Comment by UncleDave** [comment] 2017-07-24 10:31
It won't let you upload the same image twice in a row, if that's what you intend you have to clear the first image.

**Comment by armangevorgyan** [comment] 2017-07-24 10:49
No, i am limited file count to 1. and upload on image receive success from server, and browse another image for upload but it doesn't work.
i have profile picture. on hover i am showing browse button and user can chage picture , but second time he cant. after refresh he can change again 1 time

**Comment by UncleDave** [comment] 2017-07-24 11:09
If you've set `max` to 1 this sounds like the correct behaviour?
Maybe provide a snippet of your code.

**Comment by armangevorgyan** [comment] 2017-07-24 13:20
**HTML**
```
<image-upload
          [max]="1"
          [maxFileSize]="5242880"
          [url]="'http://---------/update-profile-picture'"
          [headers]="uploadHeader"h
          [partName]="'file'"
          [buttonCaption]="'browse'"
          [dropBoxMessage]="''"
          [extensions]="[]"
          [preview]="false"
          [fileTooLargeMessage]="'Wow, this is a one large file. Can you please make sure it is 5MB max?'"
          (onFileUploadFinish)="imageUploaded($event)"
          (dragover)="dragImage = true" (dragleave)="dragImage = false"
  ></image-upload>

```
**TS**

```
  imageUploaded(event: any) {
        this.dragImage = false;
        if (event.serverResponse.status !== 200) {
            this._snackBar.openFromComponent(ErrorComponent, ErrorComponent.getConfigs(5000));
        } else {
            const resp = JSON.parse(event.serverResponse._body);
            this.hideButtons();
            if (resp.success) {
                this._sharedDataService.companyLogoId = resp.response.profilePictureId;
                this._sharedDataService.companyInfo.profilePictureId = this.companyInfo.profilePictureId = resp.response.profilePictureId;
                this._companyService.getCompanyLogo(resp.response.profilePictureId).then((response) => {
                    this._sharedDataService.companyLogoURL = response;
                })
                    .catch((e) => {
                        this._snackBar.openFromComponent(ErrorComponent, ErrorComponent.getConfigs(5000));
                    });
            } else {
                for (const key in resp.errors) {
                    if (key === 'USER_PROFILE_IMAGE_UNSUPPORTED_TYPE' || key === 'USER_PROFILE_IMAGE_INVALID_FILE') {
                        this.imagePatterError = key;
                    }
                }
            }
        }

    } 
```

**Comment by armangevorgyan** [comment] 2017-07-25 07:02
Why you decided close this??

**Comment by aberezkin** [comment] 2017-07-25 08:48
Because this behavior is expected and it's not a bug.

**Comment by UncleDave** [comment] 2017-07-25 09:17
Actually you closed this.
![image](https://user-images.githubusercontent.com/3244206/28564816-21d5a960-7122-11e7-9ef4-e3edd9b93222.png)
And yes, if you set max to 1 it won't let the user upload a second - what are you trying to accomplish by setting max to 1?

**Comment by armangevorgyan** [comment] 2017-07-25 12:33
No i doesn't closed this. :)
Ok, i understand what you say. 
I want set user profile picture, second time browse should change that picture. how i can do that

**Comment by aberezkin** [comment] 2017-07-25 13:14
I believe that there is no way to do that in the current version. We can add something like `[replace]=true` input to make this behavior possible. What do you think @UncleDave?

**Comment by aberezkin** [comment] 2017-07-26 03:46
@UncleDave I think that it'll mean that new images just push old images out of the array. I even think that we can use `Observable` to make new interface more convinient 'cos all that `onUpload` `onRemove` hooks become a real mess.

**Closed** 2017-07-28 15:47 UTC
Labels: needs clarification
